apiVersion: apps/v1
kind: Deployment
metadata:
  name: spotech-api
  labels:
    app: spotech-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spotech-api
  template:
    metadata:
      labels:
        app: spotech-api
    spec:
      containers:
      - name: spotech-api
        image: spotech-api
        imagePullPolicy: Never
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: spotech-api
spec:
  selector:
    app: spotech-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
