version: '3'
services:
  #API Service
  spotech_api:
    build:
      context: ./
      dockerfile: api.dockerfile
    image: spotech.io/app
    expose: 
      - "80"
    ports:
      - "3030:80"
    container_name: spotech_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: spotech_app
      SERVICE_TAGS: production
    working_dir: /var/www
    networks:
      - spotech-network

#Docker Networks
networks:
  spotech-network:
    driver: bridge