version: '3'
services:
  #API Service
  spotech_api:
    build:
      context: ./
      dockerfile: api.dockerfile
    image: spotech.io/app
    ports:
      - "3030:80"
    container_name: spotech_app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: spotech_app
      SERVICE_TAGS: production
    working_dir: /var/www/api
    networks:
      - spotech-network
  spotech_front:
    build:
      context: ./
      dockerfile: front.dockerfile
    image: spotech.io/front
    ports:
      - "3030:80"
    container_name: spotech_front
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: spotech_front
      SERVICE_TAGS: production
    working_dir: /var/www/front
    networks:
      - spotech-network

#Docker Networks
networks:
  spotech-network:
    driver: bridge