version: '3'
services:
  #API Service
  spotech-api:
    build:
      context: ./
      dockerfile: api.dockerfile
    image: chidungdekiemtra/spotech-api
    expose: 
      - "80"
    ports:
      - "3030:80"
    container_name: spotech-api
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: spotech-api
      SERVICE_TAGS: production
    working_dir: /var/www
    networks:
      - spotech-network
  spotech-frontend:
    build:
      context: ./
      dockerfile: frontend.dockerfile
    image: chidungdekiemtra/spotech-frontend
    expose: 
      - "3000"
    ports:
      - "3000:3000"
    container_name: spotech-frontend
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: spotech-frontend
      SERVICE_TAGS: production
    working_dir: /var/www
    networks:
      - spotech-network
#Docker Networks
networks:
  spotech-network:
    driver: bridge